version: '3.9'
services:
  astra_dev:
    container_name: astra_dev
    image: ghcr.io/aduggan-syna/astra_dev:v1.6.0
    platform: linux/arm64
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/synap:/dev/synap
    volumes:
      - /home/syna:/home/syna
      - /home/root:/home/root
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
